
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: api 

on:
  push:
    branches:
      - main
    paths:
      - 'TodoApi/**'
      - '**api.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "github.run_id ${{github.run_id}}"
      - run: echo "github.run_number ${{github.run_number}}"
      - run: echo "github.run_attempt ${{github.run_attemp}}"
      - run: echo "github.sha ${{github.sha}}"
      - run: echo "GitHub Context ${{github.sha}}"
      - run: echo $(echo ${{github.event.commits[0].timestamp}})
      - run: echo $(echo ${{github.event.commits[0].timestamp}} | cut -d "T" -f1)
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './TodoApi/appsettings.json'
        env:
          AllowedCors: https://purple-cliff-0e2c19103.azurestaticapps.net/
          VersionInfo.RunNumber: ${{github.run_number}}
          VersionInfo.SHA: ${{github.sha}}
          VersionInfo.TimeStamp: ${{github.run_number}}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./TodoApi/TodoApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./TodoApi/TodoApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-dotnet6-api-angular-todolist'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DF5CFBAC330C427CADFF46D63909F465 }}
          package: .
