name: .NET API

on:
  push:
    paths:
      - 'TodoApi/**'
      - '**dotnet-api.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: dotnet6-api-angular-todolist-api    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies Api
      run: dotnet restore ./TodoApi/TodoApi.csproj
    - name: Build Api
      run: dotnet build ./TodoApi/TodoApi.csproj --no-restore --configuration Release
    - name: Publish Api
      run: dotnet publish ./TodoApi/TodoApi.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    - name: Test Web
      run: dotnet test ./TodoApi/TodoApi.csproj --no-build --verbosity normal
    # Deploy to Azure Web apps
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

