on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: x-danma/hello-world-javascript-action@1.0.11
        with:
          who-to-greet: 'Mona the Octocat'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repositoryName: ${{ github.event.repository.name }}
          sha: ${{ github.sha }}
          repositoryOwner: ${{ github.repository_owner }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
