on:
  push:
    branches:
        - 'main'
  release:
    types: [published]

jobs:

  test1:
      runs-on: windows-latest
      name: test1
      steps:
        - run: echo '${{ toJSON(github) }}'

  autoBump_tag:
    if: ${{ github.event_name == 'push' && github.run_attempt == '1' }}
    runs-on: ubuntu-latest
    name: A job to increment tag
    steps:
      - name: Increment SemVer Patch Version and Tag
        id: createTag
        uses: x-danma/increment-semver-patch-and-tag-action@1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repositoryName: ${{ github.event.repository.name }}
          sha: ${{ github.sha }}
          repositoryOwner: ${{ github.repository_owner }}
      # Use the output from the `createTag` step
      - name: Get the output tag
        run: echo "The new tag was ${{ steps.createTag.outputs.newTag }}"
  
  deploy:
    needs: autoBump_tag
    runs-on: windows-latest
    name: test1
    steps:
      - run: echo 'deploying...'